### ISSUE TITLE
Distinguish between bulk and single cell experiments

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/atlas-ingest#10]
It would be good if we can have an extra column that shows for each experiment if it is bulk or single cell. I think this should be easy for the post-processing experiment because the location will be different depending on whether they are single cell or bulk. 
For the pre-processing it will be harder based on location although some may give a clue (e.g. the GEO importer has two different paths). We could check the experiment type for those (e.g. if we find "RNA-seq of coding RNA from single cells").

**Comment by hewgreen** [comment]
This has been resolved.
