### ISSUE TITLE
Validation checks on the level of Atlas domain model, it's not just a MAGETAB file

### ISSUE THREAD

**Issue by wbazant** [ebi-gene-expression-group/atlas-ingest#2]
You're written MAGETAB validation for after the curator is done, but this is not quite what you need: if I remember correctly there's also the "configuration file" and the "contrasts file" and most likely, the problems are going to be at that interface.

In my project, I have a module representing a rectangular file in a format similar to MAGETAB, and it knows how to check its content:
https://github.com/WormBase/wbps-expression/blob/master/lib/WbpsExpression/Study/Design.pm#L250

This isn't the only thing - there are lots of other checks:
https://github.com/WormBase/wbps-expression/blob/master/lib/WbpsExpression/Study.pm#L193
For example, if the contrast refers to an assay group that doesn't exist, it should fail. Or if an assay group has less than three assays, it should perhaps also fail.

I remember I've tried to add something like this on the level of Atlas webapp. The webapp isn't really the place for checking the correctness of metadata: the curators need to be told as fast as possible, but that's what was practically possible at the time.

 I remember I have added one check that was something the webapp expected but not what the curators thought is invalid. It prevented an experiment from loading and Laura got super upset because I had no authority to be inventing strange and maddening rules. So work with curators when developing any checks on the results of their work.

**Comment by hewgreen** [comment]
Hi Wojtek,

config and contrasts are bulk atlas specific. In the single cell world we do things a little differently and don't have these steps, so you're seeing a bit of a hybrid between a few ingest routes and experiment types here. We also have a couple of validators kicking around at the moment. Hopefully the newest one will meet our ever evolving needs. When tested this will be added to these fungible workflows.

Exactly where to place it in the workflows is not set in stone. We would probably would be wise to run it every time a manual edit is done. This may depend on exactly how the new validator is parameterised.

As much as possible we are trying to tie down schema and make the validator as decoupled as possible. I think it will be sat in it's own repository soon. From there is may be useful to you. Unfortunately this repo is quite Atlas specific and not very widely useful.

Thanks again,

Matt
