### ISSUE TITLE
Time stamp for "post analysis" tab

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/atlas-ingest#9]
I've noticed that the time stamp column "Last modified" currently shows 2019-10-12 for almost all of them. 
I thought this was weird but apparently all files get copied again to the "published" folder for every release. So the date doesn't really reflect the last time when a curator touched the experiment. We'll need to think about how useful this is and if we can find a better way or if this is what we want. 
Update: According to Pablo, the time stamp of the SDRF in the "published" folder does not change and reflects when the SDRF was last modified by a curator. So we could maybe used that instead. However, we wouldn't record any updates to the IDF or configuration.

**Comment by hewgreen** [comment]
Thanks Anja. This is now tracked in pivotal.
